# Render Blueprint for WorkFlow Backend
# Reference: https://render.com/docs/blueprint-spec

services:
  - type: web
    name: workflow-backend
    env: node
    region: oregon # or your preferred region
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://your-frontend-url.vercel.app # Update this after deploying frontend
      # Add other environment variables from .env.example as needed
    healthCheckPath: /api/health
    autoDeploy: true
    branch: main # or your main branch name
